### ISSUE TITLE
Not able to run demo 

### ISSUE THREAD

**Issue by vanducng** [innovatrics/dot-js-kit#1]
Hi team,
Can you please check if we need additional preact and mask components to get project up and running.

![image](https://user-images.githubusercontent.com/2980905/117638238-d0c51400-b1ac-11eb-8eba-7b43e6c2e055.png)

Below is the error I got:
![image](https://user-images.githubusercontent.com/2980905/117638323-e8040180-b1ac-11eb-9b59-ee6efb140034.png)

**Comment by jmuravsky** [comment]
The demo itself was fixed in 1.0.7 and info on how to run it was added to README.
