### ISSUE TITLE
Can't find `sam.wasm` file

### ISSUE THREAD

**Issue by x4d3** [innovatrics/dot-js-kit#3]
Hello,

I've been following the instructions [here](https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-web-document/latest/documentation/#_introduction) in order to use  `dot-document-auto-capture`

I've downloaded the latest library from https://github.com/innovatrics/dot-js-kit/releases

I've bootstrap a react project using create-react-app generator 

But I'm getting this error
```
RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info
```

You may found a reproductible example here:

https://github.com/x4d3/hello-dot-js-kit

```
import './App.css';
import {useEffect} from "react";
import 'dot-document-auto-capture';

const DocumentCamera = (props) => {
  useEffect(() => {
    const documentAutoCaptureHTMLElement = document.getElementById('x-dot-document-auto-capture');
    if(documentAutoCaptureHTMLElement){
      console.log(documentAutoCaptureHTMLElement)
      documentAutoCaptureHTMLElement.cameraOptions = props;
    }else{
      console.log("documentAutoCaptureHTMLElement not found")
    }
  })

  return <x-dot-document-auto-capture id="x-dot-document-auto-capture" />;
};

const modelUrls = {
  modelJSON: '/hello-dot-js-kit/blaze_model/model.json',
  modelBin: '/hello-dot-js-kit/blaze_model/group1-shard1of1.bin',
};

const App = () => {

  const handleDocumentPhotoTaken = (image, resolution) => {
    console.log("handleDocumentPhotoTaken")
    console.log({image, resolution})
  };

  return (
    <div className="container" style={{height: 500, width: 500}}>
      <div>Camera</div>
      <DocumentCamera
        imageType="png"
        cameraFacing="environment"
        photoTakenCb={handleDocumentPhotoTaken}
        modelUrls={modelUrls}
      />
    </div>
  );
};


export default App;
```

Thank you for your help

**Comment by x4d3** [comment]
I think I see where the error is, the script is tryong to load a "sam.wasm" that does not exist.
The `expected magic word 00 61 73 6d` is a red hearings, as the script is trying to load a `sam.wasm`

in `/hello-dot-js-kit/static/js` but it's returning a html file in the dev env because it can't find the ressource.

I'll update the title

**Comment by x4d3** [comment]
I've added the `sam.wasm` extracted from `dot-document-auto-capture-lib.tgz` in my `public/static/js` folder in order to be where it's awaited js files, and it's now working.

I suppose there should be some kind of mecanism to package/deploy the `sam.wasm` file part of the library.

Thanks

**Comment by butoramatus** [comment]
@x4d3 by default `sam.wasm` should be in `public/` folder https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-web-document/latest/documentation/#_sam_wasm. 

In version `2.3.1` you can provide property `samWasmUrl` in `cameraOptions` to specify location of the file. However it still needs to be under `public/` folder.

https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-web-document/latest/documentation/#_properties you can provide
