### ISSUE TITLE
How to import 

### ISSUE THREAD

**Issue by simionrobert** [innovatrics/dot-js-kit#5]
How can I import **x-dot-document-auto-capture** according to 
https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-web-document/latest/documentation/#_usage
It says
```
Property 'x-dot-document-auto-capture' does not exist on type 'JSX.IntrinsicElements'
```

Here is my component
```
import * as React from "react";
import  'dot-document-auto-capture';
import { useEffect } from "react";

const DocumentCamera = (props: any) => {
  useEffect(() => {
    const documentAutoCaptureHTMLElement = document.getElementById(
      "x-dot-document-auto-capture"
    );
    (documentAutoCaptureHTMLElement as any).cameraOptions = props;
  });

  return <x-dot-document-auto-capture id="x-dot-document-auto-capture" />;
};

const modelUrls = {
  modelJSON: "blaze_model/docu_3cl_background/model.json",
  modelBin: "blaze_model/docu_3cl_background/group1-shard1of1.bin",
};

export const Page = () => {
  const handleDocumentPhotoTaken = (image: any, resolution: any) => {
    // ...
  };

  return (
    <DocumentCamera
      imageType="png"
      cameraFacing="environment"
      photoTakenCb={handleDocumentPhotoTaken}
      modelUrls={modelUrls}
    />
  );
};
```

Here is my package.json
```
 "dependencies": {
...
 "dot-document-auto-capture": "https://github.com/innovatrics/dot-js-kit/releases/download/v2.3.1/dot-document-auto-capture-lib.tgz",
    "dot-face-auto-capture": "https://github.com/innovatrics/dot-js-kit/releases/download/v2.3.1/dot-face-auto-capture-lib.tgz",
...
}
```

**Comment by butoramatus** [comment]
Hey @simionrobert , it's typescript issue. We are currently working on better solution and also preparing better samples how to integrate the components. Meanwhile you can add following to your component/types.

`declare global {
  namespace JSX {
    interface IntrinsicElements {
      "x-dot-document-auto-capture": HTMLAttributes<DocumentCameraProps>;
      "x-dot-face-auto-capture": HTMLAttributes<FaceCameraProps>;
    }
  }
}

`

**Comment by simionrobert** [comment]
Hi @butoramatus. 
Thank you for your help. 
Declaring the any types worked. 
However, declaring DocumentCameraProps didn't because "common/types" was not found in the node_modules

Nevertheless, it worked. 
You can close the issue now.

**Comment by butoramatus** [comment]
@simionrobert Alright, no problem. We are doing some rework, so we will look into it.

**Comment by butoramatus** [comment]
https://github.com/innovatrics/dot-js-kit/issues/5#issuecomment-1019857071
