### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by simionrobert** [innovatrics/dot-js-kit#7]
Please update the documentation links from readme.

```
dot.pages.innovatrics.net’s server IP address could not be found.
```

**Comment by simionrobert** [comment]
The documentation links are:
https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-web-document/latest/documentation/
and
https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-web-face/latest/documentation/

**Comment by StigoSvK** [comment]
Hi, thanks for comment. Links were updated
