### ISSUE TITLE
Open camera with camera quality error

### ISSUE THREAD

**Issue by PhuocMinhcs** [innovatrics/dot-js-kit#8]
Hi all,
I'm developer from Home Credit and I'm facing this issue when I trying to request the camera permission

Reproduce steps:
1/ open the browser prompt popup with this code below
`navigator.mediaDevices.getUserMedia(constraints)`
![image](https://user-images.githubusercontent.com/25609082/220032787-c6398523-e776-461b-bf6e-df9776eca739.png)

2/ Click the close button on the popup and open the camera component then continue use the code above to open the popup again. After that choose allow and the error will happen
![image](https://user-images.githubusercontent.com/25609082/220089927-e6a3401c-9d9f-425b-a99b-805addc47682.png)

Testing device: Chrome + window 10
"@innovatrics/dot-document-auto-capture": "^3.5.2",
 "@innovatrics/dot-face-auto-capture": "^3.5.2",
 
**Noted:  The AutoCapture component work normally if I allow permission at first time 

Please notify me via this email: minh.phamp@homecredit.vn
Thanks.

**Comment by StigoSvK** [comment]
Hi. Please contact us via [customer support](https://support.innovatrics.com/support/home)
This repo is only for components distribution. Thanks
